# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b9e2a85d568bfb7b8070b3789114d81768257d37a7932c3c257c7f1688a79af907895f37f36b4b46b24af9cb60e746f41b97ecd3bab2933552c8c13ecd987ee

test:
  secret_key_base: 490b9ab023353b3678f2a88e83c88ec6fc3e18b59aea77f17c82afa6622c5da0526c5c4673582dcd512c99936d7546adfe0bb76c9faa4fe803b8bab7981ef072

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
